# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.srcs/sources_1/bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0.xci
# IP: The module: 'System_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.gen/sources_1/bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.gen/sources_1/bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.gen/sources_1/bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.srcs/sources_1/bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0.xci
# IP: The module: 'System_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.gen/sources_1/bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.gen/sources_1/bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.gen/sources_1/bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
