


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package Simulation_axi4stream_vip_slv_0_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter Simulation_axi4stream_vip_slv_0_VIP_INTERFACE_MODE     = 2;
      parameter Simulation_axi4stream_vip_slv_0_VIP_SIGNAL_SET         = 8'b10010011;
      parameter Simulation_axi4stream_vip_slv_0_VIP_DATA_WIDTH         = 24;
      parameter Simulation_axi4stream_vip_slv_0_VIP_ID_WIDTH           = 0;
      parameter Simulation_axi4stream_vip_slv_0_VIP_DEST_WIDTH         = 0;
      parameter Simulation_axi4stream_vip_slv_0_VIP_USER_WIDTH         = 1;
      parameter Simulation_axi4stream_vip_slv_0_VIP_USER_BITS_PER_BYTE = 0;
      parameter Simulation_axi4stream_vip_slv_0_VIP_HAS_TREADY         = 1;
      parameter Simulation_axi4stream_vip_slv_0_VIP_HAS_TSTRB          = 0;
      parameter Simulation_axi4stream_vip_slv_0_VIP_HAS_TKEEP          = 0;
      parameter Simulation_axi4stream_vip_slv_0_VIP_HAS_TLAST          = 1;
      parameter Simulation_axi4stream_vip_slv_0_VIP_HAS_ACLKEN         = 0;
      parameter Simulation_axi4stream_vip_slv_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi4stream_slv_agent #(Simulation_axi4stream_vip_slv_0_VIP_SIGNAL_SET, 
                        Simulation_axi4stream_vip_slv_0_VIP_DEST_WIDTH,
                        Simulation_axi4stream_vip_slv_0_VIP_DATA_WIDTH,
                        Simulation_axi4stream_vip_slv_0_VIP_ID_WIDTH,
                        Simulation_axi4stream_vip_slv_0_VIP_USER_WIDTH, 
                        Simulation_axi4stream_vip_slv_0_VIP_USER_BITS_PER_BYTE,
                        Simulation_axi4stream_vip_slv_0_VIP_HAS_ARESETN) Simulation_axi4stream_vip_slv_0_slv_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      Simulation_axi4stream_vip_slv_0_slv_t  Simulation_axi4stream_vip_slv_0_slv;
//      initial begin : START_Simulation_axi4stream_vip_slv_0_SLAVE
//        Simulation_axi4stream_vip_slv_0_slv = new("Simulation_axi4stream_vip_slv_0_slv", `Simulation_axi4stream_vip_slv_0_PATH_TO_INTERFACE);
//        Simulation_axi4stream_vip_slv_0_slv.start_slave();
//      end

endpackage : Simulation_axi4stream_vip_slv_0_pkg
