# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/System.xdc

# Block Designs: bd/System/System.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System || ORIG_REF_NAME==System} -quiet] -quiet

# IP: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0} -quiet] -quiet

# IP: bd/System/ip/System_rst_ProcessingSystem_100M_0/System_rst_ProcessingSystem_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_rst_ProcessingSystem_100M_0 || ORIG_REF_NAME==System_rst_ProcessingSystem_100M_0} -quiet] -quiet

# IP: bd/System/ip/System_Reset_ProcessingSystem_0/System_Reset_ProcessingSystem_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_Reset_ProcessingSystem_0 || ORIG_REF_NAME==System_Reset_ProcessingSystem_0} -quiet] -quiet

# IP: bd/System/ip/System_ProcessingSystem_axi_periph_1/System_ProcessingSystem_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_ProcessingSystem_axi_periph_1 || ORIG_REF_NAME==System_ProcessingSystem_axi_periph_1} -quiet] -quiet

# IP: bd/System/ip/System_xbar_0/System_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_xbar_0 || ORIG_REF_NAME==System_xbar_0} -quiet] -quiet

# IP: bd/System/ip/System_AXIS_I2S_Receiver_0_0/System_AXIS_I2S_Receiver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_AXIS_I2S_Receiver_0_0 || ORIG_REF_NAME==System_AXIS_I2S_Receiver_0_0} -quiet] -quiet

# IP: bd/System/ip/System_axi_mem_intercon_0/System_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_axi_mem_intercon_0 || ORIG_REF_NAME==System_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/System/ip/System_auto_pc_0/System_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_auto_pc_0 || ORIG_REF_NAME==System_auto_pc_0} -quiet] -quiet

# IP: bd/System/ip/System_auto_pc_1/System_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_auto_pc_1 || ORIG_REF_NAME==System_auto_pc_1} -quiet] -quiet

# IP: bd/System/ip/System_axi_dma_0_0/System_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_axi_dma_0_0 || ORIG_REF_NAME==System_axi_dma_0_0} -quiet] -quiet

# XDC: bd/System/System_ooc.xdc
