# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/System.xdc

# Block Designs: bd/System/System.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System || ORIG_REF_NAME==System} -quiet] -quiet

# IP: bd/System/ip/System_rst_ProcessingSystem_50M_0/System_rst_ProcessingSystem_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_rst_ProcessingSystem_50M_0 || ORIG_REF_NAME==System_rst_ProcessingSystem_50M_0} -quiet] -quiet

# IP: bd/System/ip/System_processing_system7_0_1/System_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_processing_system7_0_1 || ORIG_REF_NAME==System_processing_system7_0_1} -quiet] -quiet

# IP: bd/System/ip/System_xlconcat_0_0/System_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_xlconcat_0_0 || ORIG_REF_NAME==System_xlconcat_0_0} -quiet] -quiet

# IP: bd/System/ip/System_Reset_ProcessingSystem_0/System_Reset_ProcessingSystem_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_Reset_ProcessingSystem_0 || ORIG_REF_NAME==System_Reset_ProcessingSystem_0} -quiet] -quiet

# IP: bd/System/ip/System_Reset_Video_0/System_Reset_Video_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_Reset_Video_0 || ORIG_REF_NAME==System_Reset_Video_0} -quiet] -quiet

# IP: bd/System/ip/System_VGA_Decimate_0_0/System_VGA_Decimate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_VGA_Decimate_0_0 || ORIG_REF_NAME==System_VGA_Decimate_0_0} -quiet] -quiet

# IP: bd/System/ip/System_AXI_GPIO_Input_0/System_AXI_GPIO_Input_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_AXI_GPIO_Input_0 || ORIG_REF_NAME==System_AXI_GPIO_Input_0} -quiet] -quiet

# IP: bd/System/ip/System_xbar_4_1/System_xbar_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_xbar_4 || ORIG_REF_NAME==System_xbar_4} -quiet] -quiet

# IP: bd/System/ip/System_ProcessingSystem_axi_periph_1/System_ProcessingSystem_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_ProcessingSystem_axi_periph_1 || ORIG_REF_NAME==System_ProcessingSystem_axi_periph_1} -quiet] -quiet

# IP: bd/System/ip/System_VDMA_Display_0/System_VDMA_Display_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_VDMA_Display_0 || ORIG_REF_NAME==System_VDMA_Display_0} -quiet] -quiet

# IP: bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_axi_gpio_0_0 || ORIG_REF_NAME==System_axi_gpio_0_0} -quiet] -quiet

# IP: bd/System/ip/System_xbar_5_1/System_xbar_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_xbar_5 || ORIG_REF_NAME==System_xbar_5} -quiet] -quiet

# IP: bd/System/ip/System_axi_mem_intercon_1/System_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_axi_mem_intercon_1 || ORIG_REF_NAME==System_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/System/ip/System_axi_vdma_0_0/System_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_axi_vdma_0_0 || ORIG_REF_NAME==System_axi_vdma_0_0} -quiet] -quiet

# IP: bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_clk_wiz_0_0 || ORIG_REF_NAME==System_clk_wiz_0_0} -quiet] -quiet

# IP: bd/System/ip/System_v_axi4s_vid_out_0_0/System_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==System_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/System/ip/System_v_tc_0_0/System_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_v_tc_0_0 || ORIG_REF_NAME==System_v_tc_0_0} -quiet] -quiet

# IP: bd/System/ip/System_OV7670_0_0/System_OV7670_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_OV7670_0_0 || ORIG_REF_NAME==System_OV7670_0_0} -quiet] -quiet

# IP: bd/System/ip/System_auto_pc_0/System_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_auto_pc_0 || ORIG_REF_NAME==System_auto_pc_0} -quiet] -quiet

# IP: bd/System/ip/System_auto_us_0/System_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_auto_us_0 || ORIG_REF_NAME==System_auto_us_0} -quiet] -quiet

# IP: bd/System/ip/System_auto_pc_1/System_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_auto_pc_1 || ORIG_REF_NAME==System_auto_pc_1} -quiet] -quiet

# XDC: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.gen/sources_1/bd/System/System_ooc.xdc
