# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/System/System.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System || ORIG_REF_NAME==System} -quiet] -quiet

# IP: bd/System/ip/System_processing_system7_0_1/System_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_processing_system7_0_1 || ORIG_REF_NAME==System_processing_system7_0_1} -quiet] -quiet

# XDC: h:/NextCloud/Git/ZYBO/examples/DualCore/hardware/DualCore.gen/sources_1/bd/System/System_ooc.xdc
