# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/NextCloud/Git/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.srcs/sources_1/bd/System/ip/System_rst_ProcessingSystem_50M_0/System_rst_ProcessingSystem_50M_0.xci
# IP: The module: 'System_rst_ProcessingSystem_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/NextCloud/Git/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.srcs/sources_1/bd/System/ip/System_rst_ProcessingSystem_50M_0/System_rst_ProcessingSystem_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_rst_ProcessingSystem_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: h:/NextCloud/Git/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.srcs/sources_1/bd/System/ip/System_rst_ProcessingSystem_50M_0/System_rst_ProcessingSystem_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_rst_ProcessingSystem_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: h:/NextCloud/Git/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.srcs/sources_1/bd/System/ip/System_rst_ProcessingSystem_50M_0/System_rst_ProcessingSystem_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_rst_ProcessingSystem_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: H:/NextCloud/Git/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.srcs/sources_1/bd/System/ip/System_rst_ProcessingSystem_50M_0/System_rst_ProcessingSystem_50M_0.xci
# IP: The module: 'System_rst_ProcessingSystem_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/NextCloud/Git/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.srcs/sources_1/bd/System/ip/System_rst_ProcessingSystem_50M_0/System_rst_ProcessingSystem_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_rst_ProcessingSystem_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: h:/NextCloud/Git/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.srcs/sources_1/bd/System/ip/System_rst_ProcessingSystem_50M_0/System_rst_ProcessingSystem_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_rst_ProcessingSystem_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: h:/NextCloud/Git/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.srcs/sources_1/bd/System/ip/System_rst_ProcessingSystem_50M_0/System_rst_ProcessingSystem_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_rst_ProcessingSystem_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
