
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "ov7670.h"

/*
* The configuration table for devices
*/

OV7670_Config OV7670_ConfigTable[XPAR_OV7670_NUM_INSTANCES] =
{
	{
		XPAR_OV7670_DEVICE_ID,
		XPAR_OV7670_BASEADDR,
		XPAR_OV7670_IMAGE_WIDTH,
		XPAR_OV7670_IMAGE_HEIGHT
	}
};


