# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.srcs/sources_1/bd/System/ip/System_OV7670_0_0/System_OV7670_0_0.xci
# IP: The module: 'System_OV7670_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.gen/sources_1/bd/System/ip/System_OV7670_0_0/src/Video_FIFO/Video_FIFO.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Video_FIFO || ORIG_REF_NAME==Video_FIFO} -quiet] -quiet

# XDC: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.gen/sources_1/bd/System/ip/System_OV7670_0_0/src/Video_FIFO/Video_FIFO.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Video_FIFO || ORIG_REF_NAME==Video_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.gen/sources_1/bd/System/ip/System_OV7670_0_0/src/Video_FIFO/Video_FIFO_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Video_FIFO || ORIG_REF_NAME==Video_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.srcs/sources_1/bd/System/ip/System_OV7670_0_0/System_OV7670_0_0.xci
# IP: The module: 'System_OV7670_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.gen/sources_1/bd/System/ip/System_OV7670_0_0/src/Video_FIFO/Video_FIFO.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Video_FIFO || ORIG_REF_NAME==Video_FIFO} -quiet] -quiet

# XDC: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.gen/sources_1/bd/System/ip/System_OV7670_0_0/src/Video_FIFO/Video_FIFO.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Video_FIFO || ORIG_REF_NAME==Video_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/daniel/Projects/ZYBO/projects/DigitalVideo/projects/CameraViewer/hardware/CameraViewer.gen/sources_1/bd/System/ip/System_OV7670_0_0/src/Video_FIFO/Video_FIFO_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Video_FIFO || ORIG_REF_NAME==Video_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
