# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/NextCloud/Git/ZYBO/projects/DigitalAudio/projects/I2S_AudioRecorder/hardware/I2S_AudioRecorder.srcs/sources_1/bd/System/ip/System_auto_pc_1/System_auto_pc_1.xci
# IP: The module: 'System_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/NextCloud/Git/ZYBO/projects/DigitalAudio/projects/I2S_AudioRecorder/hardware/I2S_AudioRecorder.srcs/sources_1/bd/System/ip/System_auto_pc_1/System_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: h:/NextCloud/Git/ZYBO/projects/DigitalAudio/projects/I2S_AudioRecorder/hardware/I2S_AudioRecorder.srcs/sources_1/bd/System/ip/System_auto_pc_1/System_auto_pc_1.xci
# IP: The module: 'System_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/NextCloud/Git/ZYBO/projects/DigitalAudio/projects/I2S_AudioRecorder/hardware/I2S_AudioRecorder.srcs/sources_1/bd/System/ip/System_auto_pc_1/System_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
