webtalk_init -webtalk_dir H:/NextCloud/Git/ZYBO/projects/DigitalAudio/ip_project/AXIS-I2S-Receiver/AXIS-I2S-Receiver.sim/Receiver/behav/xsim/xsim.dir/Receiver_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jul 22 21:07:17 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210727995_1777512417_210616669_543" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0e349667-9380-40ac-bb64-9df8a330a01a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "20fb8d8f55fa480d95ea810ffc33cf2c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "6.20_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "18892_KB" -context "xsim\\usage"
webtalk_transmit -clientid 929229646 -regid "210727995_1777512417_210616669_543" -xml H:/NextCloud/Git/ZYBO/projects/DigitalAudio/ip_project/AXIS-I2S-Receiver/AXIS-I2S-Receiver.sim/Receiver/behav/xsim/xsim.dir/Receiver_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html H:/NextCloud/Git/ZYBO/projects/DigitalAudio/ip_project/AXIS-I2S-Receiver/AXIS-I2S-Receiver.sim/Receiver/behav/xsim/xsim.dir/Receiver_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm H:/NextCloud/Git/ZYBO/projects/DigitalAudio/ip_project/AXIS-I2S-Receiver/AXIS-I2S-Receiver.sim/Receiver/behav/xsim/xsim.dir/Receiver_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
